export const SAMPLE_DATA = [
  {
    id: "1",
    title: "Sunset Over the Hills",
    description:
      "A beautiful painting capturing the colors of the sunset over rolling hills.",
    hastags: ["#sunset", "#landscape", "#painting"],
    likes: ["user1", "user2", "user3"],
    comments: ["Amazing work!", "Love the colors!", "So peaceful!"],
    author: "artist123",
    imageUrl: "https://via.assets.so/game.png?id=1&q=95&w=360&h=360&fit=fill",
    location: {
      latitude: 34.052235,
      longitude: -118.243683,
      altitude: null,
      accuracy: 10,
      altitudeAccuracy: null,
      heading: null,
      speed: null,
    },
    category: "Landscape",
  },
  {
    id: "2",
    title: "Morning Dew",
    description: "A photograph of dewdrops on fresh green leaves.",
    hastags: ["#nature", "#morning", "#photography"],
    likes: ["user2", "user4", "user5"],
    comments: ["So refreshing!", "Beautiful capture!"],
    author: "photographer456",
    imageUrl: "https://via.assets.so/game.png?id=1&q=95&w=360&h=360&fit=fill",
    location: {
      latitude: 51.507351,
      longitude: -0.127758,
      altitude: null,
      accuracy: 15,
      altitudeAccuracy: null,
      heading: null,
      speed: null,
    },
    category: "Nature",
  },
  {
    id: "3",
    title: "City Lights",
    description:
      "An abstract art piece inspired by the lights of the city at night.",
    hastags: ["#abstract", "#citylights", "#art"],
    likes: ["user6", "user7"],
    comments: ["Mesmerizing!", "Great use of color contrast!"],
    author: "artist789",
    imageUrl: "https://via.assets.so/game.png?id=1&q=95&w=360&h=360&fit=fill",
    location: {
      latitude: 40.712776,
      longitude: -74.005974,
      altitude: null,
      accuracy: 20,
      altitudeAccuracy: null,
      heading: null,
      speed: null,
    },
    category: "Abstract",
  },
  {
    id: "4",
    title: "Mountain Peaks",
    description: "A stunning view of snow-capped mountains during sunrise.",
    hastags: ["#mountains", "#sunrise", "#nature"],
    likes: ["user1", "user3", "user8"],
    comments: ["Breathtaking!", "Feels so peaceful."],
    author: "nature_lover",
    imageUrl: "https://via.assets.so/game.png?id=1&q=95&w=360&h=360&fit=fill",
    location: {
      latitude: 39.739236,
      longitude: -104.990251,
      altitude: null,
      accuracy: 25,
      altitudeAccuracy: null,
      heading: null,
      speed: null,
    },
    category: "Landscape",
  },
  {
    id: "5",
    title: "Autumn Leaves",
    description: "A digital artwork depicting vibrant autumn leaves falling.",
    hastags: ["#autumn", "#digitalart", "#leaves"],
    likes: ["user9", "user2", "user10"],
    comments: ["Amazing colors!", "So detailed!"],
    author: "artist456",
    imageUrl: "https://via.assets.so/game.png?id=1&q=95&w=360&h=360&fit=fill",
    location: {
      latitude: 48.856613,
      longitude: 2.352222,
      altitude: null,
      accuracy: 18,
      altitudeAccuracy: null,
      heading: null,
      speed: null,
    },
    category: "Digital Art",
  },
  {
    id: "6",
    title: "Desert Mirage",
    description:
      "An oil painting showing the beauty of the desert and its mirages.",
    hastags: ["#desert", "#oilpainting", "#mirage"],
    likes: ["user4", "user1"],
    comments: ["Feels so real!", "Incredible technique."],
    author: "painter007",
    imageUrl: "https://via.assets.so/game.png?id=1&q=95&w=360&h=360&fit=fill",
    location: {
      latitude: 25.276987,
      longitude: 55.296249,
      altitude: null,
      accuracy: 30,
      altitudeAccuracy: null,
      heading: null,
      speed: null,
    },
    category: "Oil Painting",
  },
  {
    id: "7",
    title: "Rainy Day Blues",
    description: "A melancholic watercolor piece capturing a rainy day.",
    hastags: ["#watercolor", "#rain", "#art"],
    likes: ["user8", "user3", "user6"],
    comments: ["Beautifully sad!", "Love the mood."],
    author: "artist_emotion",
    imageUrl: "https://via.assets.so/game.png?id=1&q=95&w=360&h=360&fit=fill",
    location: {
      latitude: 35.689487,
      longitude: 139.691711,
      altitude: null,
      accuracy: 12,
      altitudeAccuracy: null,
      heading: null,
      speed: null,
    },
    category: "Watercolor",
  },
  {
    id: "8",
    title: "Cherry Blossoms",
    description: "A delicate painting of cherry blossoms in full bloom.",
    hastags: ["#cherryblossoms", "#spring", "#painting"],
    likes: ["user7", "user9"],
    comments: ["So gentle!", "Spring vibes."],
    author: "floral_artist",
    imageUrl: "https://via.assets.so/game.png?id=1&q=95&w=360&h=360&fit=fill",
    location: {
      latitude: 37.774929,
      longitude: -122.419418,
      altitude: null,
      accuracy: 14,
      altitudeAccuracy: null,
      heading: null,
      speed: null,
    },
    category: "Floral",
  },
  {
    id: "9",
    title: "Ocean Waves",
    description: "A dynamic artwork of waves crashing against the shore.",
    hastags: ["#ocean", "#waves", "#art"],
    likes: ["user2", "user6", "user10"],
    comments: ["I can hear the waves!", "Powerful piece."],
    author: "seaside_artist",
    imageUrl: "https://via.assets.so/game.png?id=1&q=95&w=360&h=360&fit=fill",
    location: {
      latitude: 36.778259,
      longitude: -119.417931,
      altitude: null,
      accuracy: 20,
      altitudeAccuracy: null,
      heading: null,
      speed: null,
    },
    category: "Seascape",
  },
  {
    id: "10",
    title: "Night Sky",
    description: "A photograph of the starry night sky over a quiet lake.",
    hastags: ["#night", "#stars", "#photography"],
    likes: ["user5", "user7", "user1"],
    comments: ["So peaceful!", "Stunning view!"],
    author: "star_gazer",
    imageUrl: "https://via.assets.so/game.png?id=1&q=95&w=360&h=360&fit=fill",
    location: {
      latitude: 45.512794,
      longitude: -122.679565,
      altitude: null,
      accuracy: 22,
      altitudeAccuracy: null,
      heading: null,
      speed: null,
    },
    category: "Photography",
  },
];
